#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Nov 28 21:14:23 2018

@author: klaudia
"""

import datetime as dt
import pandas as pd
import numpy as np


def predictMissingHumidity(startDate, endDate, knownTimestamps, humidity, timestamps):
    parsed_timestamps = [dt.datetime.strptime(ts, '%Y-%m-%d %H:%M') for ts in timestamps]
    parsed_knownTimestamps = [dt.datetime.strptime(ts, '%Y-%m-%d %H:%M') for ts in knownTimestamps]
    
    s = pd.Series(humidity + [np.nan]*len(timestamps), index=parsed_knownTimestamps+parsed_timestamps)
    s = s.sort_index()
    replace_ts = s.rolling('2H').mean()
    s = s.fillna(replace_ts).fillna(s.mean())
    return s.loc[parsed_timestamps].values

if __name__ == '__main__':
    startDate = '2013-01-01'
    endDate = '2013-01-01'
    knownTimestamps= ['2013-01-01 00:00', '2013-01-01 01:00', '2013-01-01 02:00', '2013-01-01 03:00', '2013-01-01 04:00',
     '2013-01-01 05:00', '2013-01-01 06:00', '2013-01-01 08:00', '2013-01-01 10:00', '2013-01-01 11:00',
     '2013-01-01 12:00', '2013-01-01 13:00', '2013-01-01 16:00', '2013-01-01 17:00', '2013-01-01 18:00',
     '2013-01-01 19:00', '2013-01-01 20:00', '2013-01-01 21:00', '2013-01-01 23:00']
    humidity =  [0.62, 0.64, 0.62, 0.63, 0.63, 0.64, 0.63, 0.64, 0.48, 0.46, 0.45, 0.44, 0.46, 0.47, 0.48, 0.49, 0.51, 0.52, 0.52]
    timestamps =  ['2013-01-01 07:00', '2013-01-01 09:00', '2013-01-01 14:00', '2013-01-01 15:00', '2013-01-01 22:00']
    print(predictMissingHumidity(startDate, endDate, knownTimestamps, humidity, timestamps))