#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Nov 28 20:54:25 2018

@author: klaudia
"""

startDate = '2013-01-01'
endDate = '2013-01-01'
temperature = [34.38, 34.36, 34.74, 35.26, 35.23, 35.29, 35.64, 36.02, 36.1, 36.98,
               37.01, 36.75, 36.01, 35.66, 34.72, 33.9, 32.62, 31.51, 30.73, 29.5, 26.94, 25.47, 23.84, 22.55]
n = 1

p24 = len(temperature)
p = int(len(temperature)/24)

import numpy as np
X_train = np.tile(np.arange(0,24), p)
y_train = np.array(temperature)

X_test = np.tile(np.arange(0,24), n)


from sklearn import svm
clf=svm.SVR(kernel='rbf', C=100, gamma=0.1)

#X_m = np.array(months)
#Y_n = np.array(n_ppl)

X_train_r = X_train.reshape(X_train.shape[0], 1)

clf.fit(X_train_r, y_train)

#X_test = np.array(X_test)
X_test = X_test.reshape(X_test.shape[0], 1)
Y_pred=clf.predict(X_test)




from sklearn.linear_model import Ridge 
from sklearn.model_selection import train_test_split
#from sklearn.preprocessing import PolynomialFeatures
#
#    poly = PolynomialFeatures(degree = 2)
#    X_train_poly = poly.fit_transform(X_)
#    X_test_poly = poly.fit_transform(X_test)
from sklearn.linear_model import Ridge
linreg = Ridge().fit(X_train, y_train)
pred = linreg.predict(X_test_poly)



